Refactor Garden View page
beer-garden/react-ui pull request #207
Opened 2022-11-03 13:30 UTC by west270

Closes #135

Refactored to improve the page and update which table component is being used.

I added permission checks that disable the form if user does not have `garden:update` permission.
I add websocket to update data when there is a garden update which should update the garden data when someone updates the connection information or does a garden sync.

2022-11-04 14:28 UTC, jlrpnbbngtn requested changes

2022-11-04 14:28 UTC, jlrpnbbngtn commented on src/components/GardenSyncButton.tsx
> +      .then(async () => {
It's not clear why the `async` keyword was added here and below.

2022-11-04 14:28 UTC, jlrpnbbngtn commented on src/pages/GardenAdminView/GardenAdminInfoCard.tsx
> +import {
The filename should match the component name it's exporting. Whether that should be GardenAdminInfoCard or GardenInfoCard is up to you.

2022-11-04 15:03 UTC, west270 commented on src/components/GardenConnectionForm/GardenConnectionForm.tsx
> +          <fieldset disabled={!hasPermission('garden:update')}>
I test the `FormControl` and it loses the border which could be added from styling but the form can still be edited when disabled which was why I was using the `fieldset`.

2022-11-08 10:43 UTC, jlrpnbbngtn approved these changes
Thank you, looks good!

2022-11-08 10:43 UTC, merged