#172 - refactor request table
beer-garden/react-ui pull request #233
Opened 2022-11-10 16:49 UTC by obr42

Closes #172 
Closes #96 

Refactored request page to use the main table component. Was able to remove the file completely, as well as the Cache Service.

2022-11-10 19:04 UTC, knolnsokn commented
Conflicts with main

2022-11-14 17:38 UTC, jlrpnbbngtn requested changes

2022-11-14 17:38 UTC, jlrpnbbngtn commented on src/hooks/useJobs.tsx
> +  const getJobs = (): Promise<AxiosResponse<Job[]>> => {
The parameterization of the `AxiosRequestConfig` is not wrong, but it buys us nothing. I like this a lot better, though if we wanted to be pedantic we could call this `AxiosPromise<Job[]>`, which also buys us nothing over what you have here ;)

2022-11-14 18:42 UTC, jlrpnbbngtn approved these changes

2022-11-14 18:43 UTC, merged