Larger JSON results perform poorly
beer-garden/react-ui pull request #428
Opened 2023-07-07 16:37 UTC by west270

Closes #396

Changed the library used to display json data to use `react-json-view-lite` which has a better loading time than the library it is replacing. 
The component will auto collapse the values if the json data is above 700 kb to load the page faster.

For testing run a command with `output_type = "JSON"` that returns a large json value. The command `echo_message_huge_json` should be large enough to see the load time improvement but is not large enough to trigger the auto collapse.

2023-07-12 13:49 UTC, obr42 requested changes
Auto-collapse works. Noticeably faster load

2023-07-12 13:49 UTC, obr42 commented on package.json
>      "react-json-view": "^1.21.3",
If we aren't using this anywhere, can we remove?

2023-07-12 13:49 UTC, obr42 commented on src/pages/RequestView/CustomJsonViewIndex.css
> +  ._2vRm- {
I checked the purple (bool), green (null), and orange (string) in dark mode and all have < 4:1 contrast needed for accessibility. They look not too bad to me but we need 4.5:1 contrast ratio for small text to pass AA level. Since we have such fine grained control, would be nice to have follow on ticket to make them better contrast ratio if we can (or at least have the ticket out there so we can be accountable for it).

2023-07-12 13:49 UTC, obr42 commented on src/pages/RequestView/CustomJsonViewIndex.css
> +  ._2T6PJ {
I checked the green (bool), red (null), and black (string) in light mode and only the black has the >= 4.5:1 contrast needed for accessibility. I don't really like how light/bright the colors are against the white, I think a darker shade would be better. I also don't like that the string color is so close to the regular text color. Since we have such fine grained control, would be nice to have follow on ticket to make them better contrast ratio if we can (or at least have the ticket out there so we can be accountable for it).

2023-07-12 13:49 UTC, obr42 commented on src/components/JsonCard.tsx
> -import { darkTheme, lightTheme } from 'utils/customRJVThemes'
If we aren't using anymore, remove

2023-07-12 13:49 UTC, obr42 commented on src/pages/RequestView/CustomJsonViewIndex.css
> +
I feel like this should be in /components alongside the `JsonCard.tsx` or make a separate /css

2023-07-12 13:49 UTC, obr42 commented on src/setupTests.ts
> +import { TextEncoder } from 'util';
Is this related change?

2023-07-12 15:41 UTC, west270 commented on src/setupTests.ts
> +import { TextEncoder } from 'util';
Yes, the tests related to `JsonCard.tsx` fail because it of undefined reference `TextEncoder`

2023-07-14 00:40 UTC, obr42 requested changes
Just remove 'utils/customRJVThemes'

2023-07-14 13:42 UTC, obr42 approved these changes
LGTM

2023-07-14 13:43 UTC, merged