Date time picker changes
beer-garden/react-ui pull request #77
Opened 2022-07-18 12:17 UTC by west270

closes #66 

Added a default timezone for momentJS and changed the date time picker to use native pickers for better time selection. Also added to the label to indicate timezone is UTC.

To test go requests page and then open filter and select dates using date selectors.

2022-07-20 16:15 UTC, jlrpnbbngtn commented
This is a good start, but further work will commence that will try to address issues related to
1. theming, and
2. the calendar showing the current *UTC* time as its default on initial presentation.

2022-08-10 16:17 UTC, west270 commented
> This is a good start, but further work will commence that will try to address issues related to
> 
> 1. theming, and
> 2. the calendar showing the current _UTC_ time as its default on initial presentation.

The theme is working with the datetime picker. 
The default time for the modal datetime picker cannot be changed because `input` with type `datetime-local` does not support setting a timezone. A new issue can be made if someone wants to explore other datetime picker libraries that support setting a timezone.

2022-08-17 13:10 UTC, jlrpnbbngtn requested changes
Minor comments only...

2022-08-17 14:25 UTC, jlrpnbbngtn approved these changes

2022-08-17 14:26 UTC, merged